version: '2'
services: 
  php-apache:
    build:
      context: .
    ports:
      - 80:80
    volumes: 
      - ./www:/var/www/html
    environment:
      TITLE: "LAMPIE"
      TZ: "Europe/Amsterdam"

  mariadb:
    image: mariadb:10.5
    volumes: 
       - mariavol:/var/lib/mysql
    environment:
      TZ: "Europe/Amsterdam"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD:-rood}
      # overrid this to something secure when in production, with env variables or .env file
      MYSQL_DATABASE: "opvang"
      
volumes:
  mariavol:
