version: '2'
services: 
  php-apache:
    build:
      context: .
    ports:
      - 8082:80
    volumes: 
      - ./www:/var/www/html
    environment:
      TITLE: "LAMPIE"
      TZ: "Europe/Amsterdam"

  mariadb:
    image: mariadb:10.1
    volumes: 
       - mariavol:/var/lib/mysql
    environment:
      TZ: "Europe/Amsterdam"
      MYSQL_ROOT_PASSWORD: "rood"
      MYSQL_DATABASE: "opvang"
      
volumes:
  mariavol:
